/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class VentanaInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public VentanaInicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldCorreo = new javax.swing.JTextField();
        fieldClave = new javax.swing.JTextField();
        botonIniciarSesion = new javax.swing.JButton();
        botonRegistrarse = new javax.swing.JButton();
        botonOlvidadaContrasena = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¡Bienvenido a JavaEat, inicia sesión!");

        fieldCorreo.setText("Correo");
        fieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCorreoActionPerformed(evt);
            }
        });

        fieldClave.setText("Clave");

        botonIniciarSesion.setText("Iniciar sesion");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });

        botonRegistrarse.setText("Registrarme");
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });

        botonOlvidadaContrasena.setText("¿Olvidaste la contraseña?");
        botonOlvidadaContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOlvidadaContrasenaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoJavaEat (1) (1) (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonOlvidadaContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                .addGap(294, 294, 294))
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fieldClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(fieldCorreo, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIniciarSesion)
                    .addComponent(botonRegistrarse))
                .addGap(18, 18, 18)
                .addComponent(botonOlvidadaContrasena)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCorreoActionPerformed
    public boolean verificarCredenciales(String correo, String clave) {
        if (correo.equals("admin@javaeat.com") && clave.equals("admin")) {
            UsuarioActual.setTipoUsuario("Administrador");
            return true;
        } else {
            for (Particular particular : Informacion.listaParticulares) {
                if (particular.getCorreo().equals(correo) && particular.getClave().equals(clave)) {
                    UsuarioActual.setTipoUsuario("Particular");
                    return true; // las credenciales coinciden
                }
            }
            for (Empresa empresa : Informacion.listaEmpresas) {
                if (empresa.getCorreo().equals(correo) && empresa.getClave().equals(clave)) {
                    UsuarioActual.setTipoUsuario("Empresa");
                    return true; // las credenciales coinciden
                }
            }
        }
        return false; // las credenciales no coinciden
    }
    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        String correo = fieldCorreo.getText(); // obtener el correo electrónico ingresado
        String clave = fieldClave.getText(); // obtener la clave ingresada
        UsuarioActual.setCorreo(correo);
        
        if (verificarCredenciales(correo, clave)) {
            String tipoUsuario = UsuarioActual.getTipoUsuario();
            if ("Administrador".equals(tipoUsuario)) {
                VentanaAdministrador ventana = new VentanaAdministrador();
                ventana.setVisible(true);
                dispose();
            }
            if ("Particular".equals(tipoUsuario)) {
                VentanaPrincipalParticular ventana = new VentanaPrincipalParticular();
                ventana.setVisible(true);
                dispose();
            }
            if ("Empresa".equals(tipoUsuario)) {
                VentanaPrincipalEmpresa ventana = new VentanaPrincipalEmpresa();
                ventana.setVisible(true);
                dispose();
            }
        } else {
            // mostrar un mensaje de error si las credenciales son incorrectas
            JOptionPane.showMessageDialog(null, "Correo electrónico o clave incorrectos");
        }


    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
    // Mostrar cuadro de diálogo para seleccionar el tipo de usuario
    String[] opciones = {"Particular", "Empresa"};
    int seleccion = JOptionPane.showOptionDialog(this, "Seleccione el tipo de usuario", "Registro", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

    if (seleccion != JOptionPane.CLOSED_OPTION) {
        String tipoUsuario = opciones[seleccion];

        if ("Particular".equals(tipoUsuario)) {
            VentanaRegistroParticular ventana = new VentanaRegistroParticular();
            ventana.setVisible(true);
            dispose();
        }
        if ("Empresa".equals(tipoUsuario)) {
            VentanaRegistroEmpresa ventana = new VentanaRegistroEmpresa();
            ventana.setVisible(true);
            dispose();
        }
    }
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    private void botonOlvidadaContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOlvidadaContrasenaActionPerformed
        String tipoUsuario = UsuarioActual.getTipoUsuario();
        if ("Particular".equals(tipoUsuario)) {
            ContrasenaOlvidadaParticular ventana = new ContrasenaOlvidadaParticular();
            ventana.setVisible(true);
            dispose();
        }
        if ("Empresa".equals(tipoUsuario)) {
            ContrasenaOlvidadaEmpresa ventana = new ContrasenaOlvidadaEmpresa();
            ventana.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_botonOlvidadaContrasenaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaAdministrador ventana = new VentanaAdministrador();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonOlvidadaContrasena;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JTextField fieldClave;
    private javax.swing.JTextField fieldCorreo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
